### ISSUE TITLE
'\\tool_objectfs\\azure_file_system' not found

### ISSUE THREAD

**Issue by JCollicutt** [Azure/Moodle#133] opened 2018-05-25 20:41 UTC
Hello everyone,

I navigated to the Notification page (Site Administration -> Notifications) today, and noticed that it was giving me the warning message that "The cli/cron.php maintenance script has not been run for at least 24 hours."

I SSH'd to the controller VM, and attempted to manually run the cron.php file, but I got this error:

_______@controller-vm-yjp3jr:/etc/cron.d$ sudo -u www-data /usr/bin/php /moodle/html/moodle/admin/cli/cron.php
Server Time: Fri, 25 May 2018 21:24:36 +0100

Execute scheduled task: Object file system upload task (tool_objectfs\task\push_objects_to_storage)
... started 21:24:36. Current memory use 16.9MB.
!!! Exception - Class '\\tool_objectfs\\azure_file_system' not found !!!

I know in the config.php file, I have the following line:
$CFG->alternative_file_system_class = '\tool_objectfs\azure_file_system';

...but I am at a loss on how to proceed. Any ideas or suggestions would be greatly appreciative!

**Comment by hosungsmsft** [comment] 2018-05-25 21:02
Thanks for letting us know. So I assume you changed the `installObjectFsSwitch` to true when deploying the template, correct? Then could you please check on your controller VM if there's the following directory (and files/directories under it)?

```
/moodle/html/moodle/admin/tool/objectfs
```

Basically, our install script downloads/installs the Object FS plugin as described [here](https://github.com/Azure/Moodle/blob/master/scripts/install_moodle.sh#L273-L278). Currently, we rarely use/test the ObjectFS plugin ourselves, so there might have been some breaking changes unnoticed. When did you deploy our templates? That might be a factor, for another reason. In the meantime, let me try to reproduce your issue and get back here.

**Comment by JCollicutt** [comment] 2018-05-25 21:20
We would have deployed a day or two after the live stream event. I believe that was May 1st, so perhaps May 2nd or 3rd?
I believe we did set installObjectFSSwitch to true in the template. After looking at my controller VM, the directory /moodle/html/moodle/admin/tool/objectfs does exist.
version.php stats that it is version 2017111700 if that helps at all.

Thank you so much for assisting! If you need any other info at all, let me know! =)

**Comment by hosungsmsft** [comment] 2018-05-25 21:40
Thanks for providing more information. Now I get to wonder if this issue started recently, or if it was like this ever since you deployed our templates back in early May. I myself haven't used the Object FS plugin that much (please note we are not education, but mostly infra/platform), so please understand that our support might be limited. Next step I would try is to see if the plugin is installed correctly on your Moodle site (which I believe it should, because I remember enabled plugins on my earlier template deployment were correctly installed and available on the deployed Moodle site), and that'll be doable by going to Site administration - Plugins and searching for the Object FS plugin (sorry don't remember the exact plugin category and name). It might take us some time to try to repro this issue ourselves, but if you are willing, we may set up a remote screen sharing session to go over your deployment. My email address is available on my GitHub profile page, so please feel free to reach out. Thanks.

**Comment by hosungsmsft** [comment] 2018-05-25 22:42
Update: I can repro this issue myself (see the logs below), so I think this must be broken ever since you deployed our templates, and you just noticed this recently. This could be a day-0 bug for us that's revealed by your first usage of this plugin. We'll investigate this issue more and fix it.

In the meantime, if you don't need this ObjectFS plugin, then I believe you should be able to avoid this issue by uninstalling the plugin from your Site administration - Plugins page. It'd be interesting for us to know how you are using the ObjectFS plugin with Azure Storage, but of course that's not relevant to this issue. Thanks again for letting us know!

```
azureadmin@controller-vm-ro6yqj:~$ tail -10 /var/log/syslog
May 25 22:41:01 controller-vm-ro6yqj CRON[66474]: (www-data) CMD (/usr/bin/php /moodle/html/moodle/admin/cli/cron.php 2>&1 | /usr/bin/logger -p local2.notice -t moodle)
May 25 22:41:01 controller-vm-ro6yqj moodle: PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/pdo_sqlsrv.so' - /usr/lib/php/20151012/pdo_sqlsrv.so: undefined symbol: php_pdo_register_driver in Unknown on line 0
May 25 22:41:01 controller-vm-ro6yqj moodle: PHP Warning:  Module 'sqlsrv' already loaded in Unknown on line 0
May 25 22:41:01 controller-vm-ro6yqj moodle: PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/pdo_sqlsrv.so' - /usr/lib/php/20151012/pdo_sqlsrv.so: undefined symbol: php_pdo_register_driver in Unknown on line 0
May 25 22:41:02 controller-vm-ro6yqj moodle: Server Time: Fri, 25 May 2018 23:41:02 +0100
May 25 22:41:02 controller-vm-ro6yqj moodle: 
May 25 22:41:02 controller-vm-ro6yqj moodle: 
May 25 22:41:02 controller-vm-ro6yqj moodle: Execute scheduled task: Object file system upload task (tool_objectfs\task\push_objects_to_storage)
May 25 22:41:02 controller-vm-ro6yqj moodle: ... started 23:41:02. Current memory use 13.9MB.
May 25 22:41:02 controller-vm-ro6yqj moodle: !!! Exception - Class '\\tool_objectfs\\azure_file_system' not found !!!
azureadmin@controller-vm-ro6yqj:~$ 
```

**Comment by hosungsmsft** [comment] 2018-05-25 23:13
Well, I thought this issue is not related to #134, but apparently, after I fixed that issue on my test cluster, the cron job is working fine as well. I wonder if you might have hit the bug #134 yourself when you deploy the templates? We don't know exactly when the Azure CLI repo signing key is changed (only known as early May, so you might have been affected).

To confirm whether that's the case, could you please email me the screenshot of your https://lb-ro6yqj.southcentralus.cloudapp.azure.com/admin/tool/objectfs/index.php browser results, especially the Azure Blob Storage Settings section? It'd be best if you can paste the screenshot here, but I don't know how to do that on GitHub.

**Comment by JCollicutt** [comment] 2018-05-25 23:55
I hope this image comes across.

![image](https://user-images.githubusercontent.com/39634631/40570083-69c20860-6044-11e8-926f-83cc07f26dfc.png)

**Comment by hosungsmsft** [comment] 2018-05-26 01:58
I just confirmed that the issue no longer repros on me after #134 is fixed, so this issue happens only when the ObjectFS plugin is incorrectly configured. Still, it's strange how @JCollicutt's ObjectFS plugin settings were blank (assuming the plugin was installed at the deployment time), but apparently @JCollicutt also confirmed that their ObjectFS plugin settings were incorrect, so the symptom is consistent and it's not a bug on our side.

Still, ObjectFS plugin shouldn't raise an exception and terminate the cron job even if the settings are incorrect. I think this should be an ObjectFS plugin bug, so I'll file an issue there and see how it goes. Thanks and closing this as such.

**Closed by hosungsmsft** 2018-05-26 01:58 UTC
Labels: question

**Comment by hosungsmsft** [comment] 2018-05-26 02:08
Filed https://github.com/catalyst/moodle-tool_objectfs/issues/93 for this issue.
