### ISSUE TITLE
/moodle/html directory disappeared on controller VM

### ISSUE THREAD

**Issue by JCollicutt** [Azure/Moodle#154] opened 2018-08-02 21:51 UTC
Hello,

First, I'd like to apologize if I don't quite make sense. I'm still trying to wrap my head around how this all works together, and I may have false assumptions.

This morning at around 2am my controller VM had a health error about an "unexpected host server reboot." Not long after, I got a message saying "We're sorry, your virtual machine isn't available and it is being redeployed due to an unexpected failure on the host server."

From what I can tell, everything seems to be there, except for the files and directories under /moodle/ . I mounted several different backups (of the controller VM) for file recovery, but they also did not have the file/directories under /moodle/ -- Such as /moodle/html/moodle .

I do see the files in the gluster vm, so that's nice.
Was /moodle/html just a link to the gluster vm? If so, is it possible to recreate that?
If it wasn't a link...can I just copy the data from the gluster vm to the controller vm?

Any help would be greatly appreciated!
Thank you =)

**Comment by hosungsmsft** [comment] 2018-08-02 22:16
Thanks @JCollicutt for letting us know about this and I'm sorry for this issue. Yes, the `/moodle` directory is just a mount point that mounts the remote Gluster file share from the Gluster cluster. It's definitely good that you can see the `/moodle` content in a Gluster VM, but it's no good that it's not automatically mounted on the controller VM after it's rebooted/redeployed. Our deployment script configures the auto-mounting of the `/moodle` directory on the controller machine by shell commands like [this](https://github.com/Azure/Moodle/blob/master/scripts/install_moodle.sh#L160) and [this](https://github.com/Azure/Moodle/blob/master/scripts/helper_functions.sh#L119-L126). Could you send me your `/etc/fstab` file content in your controller VM (by email, not pasting here, if there's any sensitive information in it)? There should be a line starting `/moodle`, and if there's none, that's an issue and rectified separately. I'd be happy to fix the issue together with you over a remote screen-shared online meeting. If you can find a line in `/etc/fstab` that starts with `/moodle`, then it's strange that the directory is not auto-mounted on a reboot. Could you run the following command on your controller VM and see if `/moodle` is mounted/available on the VM?
```
$ sudo mount /moodle
```
Again, please feel free to contact me by email if you'd like to fix this issue more swiftly. Hopefully there's no bug here, but I can't be 100% sure at this point how this happened.

Thanks!

**Comment by hosungsmsft** [comment] 2018-08-03 15:47
Corresponded with @JCollicutt and his colleague further. It turns out that this was due to the Issue #129, which was fixed on May 24, and I think it appears that their deployment was done before that date, thus this issue shows up only after the first reboot of their controller VM.
To fix this issue manually, we need the `glusterNode` and the `glusterVolume` values from the deployment parameters. The easiest way to get them is from the logged `/tmp/vars.txt` file, so I asked them to send me the first 5 lines of that file (to exclude unrelated/sensitive fields), but it was gone unfortunately. However, luckily they had set up Azure Backup and were able to restore the file for me, so I got them. Once we obtain the two values, we can just run the shell function that's defined [here](https://github.com/Azure/Moodle/blob/master/scripts/helper_functions.sh#L119-L126), which is reproduced here for convenience:
```
function setup_and_mount_gluster_moodle_share
{
    local glusterNode=$1
    local glusterVolume=$2

    grep -q "/moodle.*glusterfs" /etc/fstab || echo -e $glusterNode':/'$glusterVolume'   /moodle         glusterfs       defaults,_netdev,log-level=WARNING,log-file=/var/log/gluster.log 0 0' >> /etc/fstab
    mount /moodle
}
```
Copy/paste the above block into your shell and run it as follows:
```
$ setup_and_mount_gluster_moodle_share <obtained_glusterNode_value> <obtained_glusterVolume_value>
```
Please note that the above commands must be executed as root (do `sudo -s` before running the commands above). For reference, the `glusterNode` value is most likely in the form of `gluster-vm-xyz123`, and the `glusterVolume` value is most likely fixed to `data`. If `/tmp/vars.txt` is gone and can't be restored, the `glusterNode` value can be found through another means like inspecting the Azure VM name for the gluster cluster.
After running these commands, the `/moodle` directory content is now available on the controller, so everything is good now. And rebooting the machine should still mount the directory as well. Closing this issue as it's fixed now. Thanks.

**Closed by hosungsmsft** 2018-08-03 15:47 UTC
