### ISSUE TITLE
Problem after installation

### ISSUE THREAD

**Issue by tiberain** [Azure/Moodle#135] opened 2018-05-29 13:49 UTC
Hey,

So I've installed the "Fully configurable deployment" (A few times with different URL's and tested on two computers) I left everything default, changed my host file.
It installed correctly no errors until I try load the site.
![image](https://user-images.githubusercontent.com/2485554/40662658-ec0f5da6-634e-11e8-99d2-d8a2eef955f2.png)

I've tried clearing cookies but not sure why I can't get it to load, I've created site in the past with no problem

**Comment by rgardler** [comment] 2018-05-29 13:53
Sounds like we may have introduced a bug with our recent changes. Can you please confirm whether you are accessing http:// or https://.

Is you are using http:// please try https://

**Comment by tiberain** [comment] 2018-05-29 14:06
Hey,

It seems to redirect to https but in my host file and in browser I don't state http or https

**Comment by hosungsmsft** [comment] 2018-05-29 15:09
So, it sounds like you specified your own `siteURL` parameter. Am I right? In that case, did you update your Moodle site's `config.php` (specifically `$CFG->wwwroot`) with your `siteURL` parameter value?

**Comment by rgardler** [comment] 2018-05-29 15:28
@hosungs that should not be necessary - if it is then I consider it a bug, our install scripts should do that for us. Lets raise an issue for it if it is required. @tiberain you can assume it is necessary since @hosungs is flagging it.

@tiberain can you please try https://, this will tell us whether the problem is in the redirect setup or elsewhere.

**Comment by hosungsmsft** [comment] 2018-05-29 15:35
@rgardler -- Thanks, you are right and I was mistaken. It shouldn't be necessary. Our script does that already (https://github.com/Azure/Moodle/blob/master/scripts/install_moodle.sh#L800). @tiberain -- Ignore what I said. You shouldn't need to update the `config.php` (`$CFG->wwwroot`) when you give `siteURL` at the deployment time. You just need to update your DNS record for the `siteURL` to point to the deployed Azure load balancer FQDN (something like `lb-pubip-xxxxxx.azure_location.cloudapp.azure.com`).

I was thinking of some other case, but thinking more, that doesn't make sense either. It feels like there's something else going on, but without fully knowing the exact DNS setup and the initial `siteURL` value, it'll be hard to find out what's going on.

**Comment by tiberain** [comment] 2018-05-30 08:36
Hey @rgardler , @hosungs ,

I havn't had this problem before I was installing and reinstalling my moodle instance to weeks ago (around the 18th of may) I might have done it last week but can't confirm that.

**Comment by rgardler** [comment] 2018-05-30 14:39
The templates are passing CI and we've deployed live sites in that time. It would seem there is something different about your configuration.

Can you please help us narrow down the problem as noted above by trying to access https:// directly and describing your DNS setup and initial site Url value. You also indicate you have edited your Hosts file, what does that now look like?

**Comment by hosungsmsft** [comment] 2018-05-30 14:52
@tiberain -- At least can you share your problematic site URL so that we can try probing the site from here (though we may not find much)? Also, it'd be good if you share your deployment parameters and DNS setup, to further investigate.

**Comment by tiberain** [comment] 2018-05-30 14:59
Hey,

 So I use the fully configurable, here are all the setting and I only change the URL.
![screenshot_49](https://user-images.githubusercontent.com/2485554/40728190-79ff657a-6421-11e8-8a7c-6a7f805a66e7.png)
![screenshot_50](https://user-images.githubusercontent.com/2485554/40728193-7b7a89f2-6421-11e8-996f-0378ab38913f.png)
![screenshot_51](https://user-images.githubusercontent.com/2485554/40728202-7dbc6af0-6421-11e8-83dc-a9e5aae75033.png)

One it installs I then add the URL into my host file with the ip of the load balancer. I've done this loads I usually create one do some tests then delete it.

**Comment by rgardler** [comment] 2018-05-30 15:19
Yes we understand what you have changed in the templates. Why we are asking for is not related to the templates. These work in our test scenarios and thus we need to understand what your environment looks like.

Please share all the information requested in previous comments or e are unable to help you.

**Comment by tiberain** [comment] 2018-05-31 08:10
Hey,

This site I've created is not public so there is DNS set or hasn't been in the past. All I've done is  added the url and ip (IP of the load balancer) my my host file **(.../ect/hosts)**
I also just created a new one :
Here is the details :  104.41.226.46 www.moodel-test-test.ie

**Comment by rgardler** [comment] 2018-05-31 14:10
Did you redeploy the cluster? I'm not aware of anything we've done in code recently that would affect this.

Did you change anything else in configuration?

**Comment by tiberain** [comment] 2018-05-31 14:49
Hey, 

Yea I did redeploy I do most days, on the day I created this thred I did it 4 times and got the error from above.
Between deployments I delete the one that is not working redeploy sometimes with the same URL as the one I just deleted sometimes without

**Comment by hosungsmsft** [comment] 2018-05-31 15:20
Thanks for letting us know. We'd be interested in knowing your use case of such frequent deployments, but all in all, using `/etc/hosts` for your deployed web sites to configure proper redirection is not a supported scenario and it should be noted that anyone who adopts such a special configuration is responsible for configuring everything correctly. We'd be happy to help even in such a case, but we also need full details to be of any help. I'm closing this issue as you confirmed that this is not repro-ing any more. If it happens again, please do make sure that your special configuration is indeed correct end-to-end, and if you want us to help, please do provide full details as we requested.

**Closed by hosungsmsft** 2018-05-31 15:20 UTC

**Comment by tiberain** [comment] 2018-06-01 09:46
Hey,

My use case is to create a moodle instance for a client that is "bullet proof" or as close as possible. It also needs to have VSTS and we need to know how to migrate from different moodle instances. 
From time to time a script or a migration breaks the site so I just delete and restart.

**Comment by ravish0007** [comment] 2020-04-06 12:35
@rgardler 
I'm a noob at Azure Cloud and First time ever I have deployed cluster, I was able to access the frontend from the browser. Need help in doing a Admin Login ASAP. Do I have to  SSH into MysqlDB server and reset the password ?

**Comment by rgardler** [comment] 2020-04-06 20:04
@ravish0007 In future, please open a separate issue for each item and don't ping individuals unless you are certain they are the people you need. This issue has been closed for nearly 2 years and is unrelated to your question.

For answers to your question see https://github.com/Azure/Moodle/blob/6cce6b2e88970dfc49a6c1fb7fd85d305eb9fe83/docs/Get-Install-Data.md
