### ISSUE TITLE
Build failing when gluster is selected as fs

### ISSUE THREAD

**Issue by taylora3** [Azure/Moodle#155] opened 2018-08-14 12:48 UTC
The template fails when builds are done using gluster fs. It is working for nfs and nfs-ha. The errors I was receiving weren't the most helpful so narrowed it down through trial and error.

**Comment by hosungsmsft** [comment] 2018-08-14 15:31
Thanks @taylora3 for letting us know. Is this failure recent (started to happen today)? I suspect my latest commit (https://github.com/Azure/Moodle/commit/2a11551ff282017320e222912903fecb7260acb2) might be causing this, and it'd be good to know if this started to happen only after that commit. I should have been more restrictive in my change and I'll commit a fix very soon.

**Comment by taylora3** [comment] 2018-08-14 16:56
I think it's been happening for a while. I believe what I thought was an issue with SSL certs and app gateway was being caused by this.

**Comment by hosungsmsft** [comment] 2018-08-14 17:04
Thanks for more info, so my latest change 4367209 is not relevant to this issue. I'll try to repro this myself, but I'll need more info on the exact configuration. Are you trying a Gluster-backed Moodle cluster with an App Gateway and getting deployment failures? If not, could you paste here your template deployment parameters (probably redacting your ssh public key, though it's not really a secret).

**Comment by taylora3** [comment] 2018-08-14 17:47
It happens when either vmss or app gateway are selected. I can send through my parameters tomorrow if that would be of assistance. Thanks for your help.

**Comment by hosungsmsft** [comment] 2018-08-14 20:28
Thanks for more info. I was able to repro this myself, and apparently it fails as below. It looks like we've been using too old a version of glusterfs and it got removed from their PPA repo sometime in recent past. I'll try another PPA and update this issue.
```
root@controller-vm-6wtbin:~# tail /var/lib/waagent/custom-script/download/0/stderr 
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
+ config_fail2ban
+ cat
+ mkdir -p /moodle
+ export DEBIAN_FRONTEND=noninteractive
+ DEBIAN_FRONTEND=noninteractive
+ '[' gluster = gluster ']'
+ sudo add-apt-repository ppa:gluster/glusterfs-3.8 -y
root@controller-vm-6wtbin:~# sudo add-apt-repository ppa:gluster/glusterfs-3.8 -y
Cannot add PPA: 'ppa:~gluster/ubuntu/glusterfs-3.8'.
The team named '~gluster' has no PPA named 'ubuntu/glusterfs-3.8'
Please choose from the following available PPAs:
 * 'glusterfs-3.10':  glusterfs-3.10
 * 'glusterfs-3.11':  glusterfs-3.11
 * 'glusterfs-3.12':  glusterfs 3.12
 * 'glusterfs-3.13':  glusterfs-3.13
 * 'glusterfs-4.0':  glusterfs-4.0
 * 'glusterfs-4.1':  glusterfs-4.1
 * 'glusterfs-coreutils':  glusterfs-coreutils
 * 'libntirpc-1.5':  libntirpc-1.5
 * 'libntirpc-1.6':  libntirpc-1.6
 * 'nfs-ganesha-2.5':  nfs-ganesha-2.5
 * 'nfs-ganesha-2.6':  nfs-ganesha-2.6
 * 'storhaug':  storhaug
root@controller-vm-6wtbin:~# echo $?
1
root@controller-vm-6wtbin:~# 
```

**Comment by hosungsmsft** [comment] 2018-08-14 22:52
@taylora3 -- I confirmed that the commit 75d1516 fixes this issue. Please confirm this yourself as well and let us know. The change was to update the glusterfs PPA version to 3.10 (3.12 doesn't work, because it uses systemd, with no `/etc/init.d/glusterfs-server` script, which our scripts currently depend on. We actually should fix the scripts for systemd, but for the sake of a quick fix, 3.10 is now used for now (and I'm afraid 3.10 might be removed not too distant future).

**Comment by taylora3** [comment] 2018-08-15 13:47
@hosungsmsft I have confirmed that the install runs to completion with gluster as fs for both VMSS and App Gateway. The SSL issue I'm having is still separate to this so I think this can be closed unless you want to leave it open for possible issues "not too distant future". Thanks for your help and speedy response on this.

**Comment by hosungsmsft** [comment] 2018-08-15 15:43
Thanks for letting me know. I'll close this issue as such. I'll file an Issue for the glusterfs PPA version so that we fix our scripts with the latest glusterfs PPA version.

I think the dbTemplate failure you pasted is a transient issue. If that persists, please do let us know, but as you can infer from the name of the resource (dbTemplate), it's deploying an Azure MySQL instance and the failure message says it timed out, so if this issue persists, we'll have to escalate it to Azure MySQL team.

I'm sorry to hear that you are still having the SSL issue. Perhaps we should sync over a remote online meeting. I've got a few ideas, but I haven't used App Gateway much myself anyway, so I'm not sure how it'll turn out. Please feel free to email me if you'd like to have an online meeting.

**Closed by hosungsmsft** 2018-08-15 15:43 UTC
