### ISSUE TITLE
First load problem

### ISSUE THREAD

**Issue by tiberain** [Azure/Moodle#144] opened 2018-06-07 08:45 UTC
Hey,

So sense yesterday evening I've been having problems with "launching" the moodle site the installation works no problem with that.
But when I first go to the site I'm being promoted to install moodle and then its says it doesn't have the rights to install in the location it wants to.

![image](https://user-images.githubusercontent.com/2485554/41088369-46643936-6a37-11e8-92a8-69c00eeb3046.png)

![image](https://user-images.githubusercontent.com/2485554/41088393-57518514-6a37-11e8-82be-cf07fba3b318.png)

**Comment by rgardler** [comment] 2018-06-07 16:16
There have been no cons to the repository lately, so this is not caused by any change here. Can you please describe reproducible steps so that we can examine the problem.

**Comment by tiberain** [comment] 2018-06-08 07:41
Hey,

Installed any deployment of the environment, open he site for the first time. That's it

**Comment by hosungsmsft** [comment] 2018-06-11 18:43
Thanks for letting us know. My latest change (#140) seems to have broken the build for non-MSSQL DBs. I'm fixing on this.

**Comment by hosungsmsft** [comment] 2018-06-11 21:08
This was a regression from #140 and is now fixed with the commit c872999e1e98b2f6014b3b315bb2878ce584d332. I'm closing this issue as such. Please reopen this issue if the issue still persists.

**Closed by hosungsmsft** 2018-06-11 21:08 UTC

**Comment by tiberain** [comment] 2018-06-12 10:13
Hey @hosungsmsft ,

That solved the moodle installation problem but re added in the premission issue for VSTS to access the root

**Comment by hosungsmsft** [comment] 2018-06-12 15:23
@tiberain -- Thanks for letting us know the issue's fixed, but I'm not sure what you mean by the VSTS permission issue recurring. Great that you pasted the screen clipping, but I'm very certain that it must be just as expected. The `/moodle/html` directory is entirely owned by root:root, and if you try to copy any files over in that directory tree as a non-root user (I'm assuming you are using a non-root user account for the VSTS ssh file copy, and I don't think you can use the root account for that), the OS will just reject that, and I'm certain that's exactly what you are seeing.

I'm puzzled to hear that this permission issue is re-appearing after the fix, and that this permission issue was gone somehow, which I don't think is possible, unless you actually did something on the deployed file system on your own. The `/moodle/html` directory has been always owned by root:root, and nothing's changed in that regard.  Please note that these are mostly the basic Unix/Linux usage stuff and I recommend utilizing web resources to find out more. I'd be happy to help you on that, but it won't be possible through this medium. If you'd like, always email me and we can set up some remote online screen sharing meeting to go through this.
